name: christina
favicon: null
layout_spectrum: 0.7737283390015364
typography_spectrum: 0.5394006746355444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5622966147493571
  lightness: 0.17177167301997542
  saturation: 0.13514299923554063
  rhythmicContrast: 0.4742671446874738
purpose: []
